polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('part1/', views.index, name='index'),
    path('part2/', views.part2, name='part2'),
    path('part3/', views.part3_index, name='part3_index'),
    path('part3/<int:question_id>/', views.part3_detail, name='part3_detail'),
    path('part3/<int:question_id>/results/', views.part3_results, name='part3_results'),
    path('part3/<int:question_id>/vote/', views.part3_vote, name='part3_vote'),
    path('part4/', views.part4_IndexView.as_view(), name='part4_index'),
    path('part4/<int:pk>/', views.part4_DetailView.as_view(), name='part4_detail'),
    path('part4/<int:pk>/results/', views.part4_ResultsView.as_view(), name='part4_results'),
    path('part4/<int:question_id>/vote/', views.part4_vote, name='part4_vote'),
    path('',views.tutorials,name="tutorials")
]

study/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('univer/', include('university.urls')),
    path('admin/', admin.site.urls),
]

polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
import html

from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
# from django.http import Http404
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic

from .models import Question, Choice

def tutorials(request):
    return render(request, 'polls/tutorials.html')

def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")

def part2(request):

    text = '''<!doctype html>
    >> > from polls.models import Choice, Question  # Import the model classes we just wrote. <br>

    # No questions are in the system yet. <br>
    >> > Question.objects.all() <br>''' + html.escape(str(Question.objects.all())) + '<br>'

    text += '''# Create a new Question. <br>
    # Support for time zones is enabled in the default settings file, so <br>
    # Django expects a datetime with tzinfo for pub_date. Use timezone.now() <br>
    # instead of datetime.datetime.now() and it will do the right thing. <br>
    
    from django.utils import timezone <br>
    >> > q = Question(question_text="What's new?", pub_date=timezone.now()) <br>

    # Save the object into the database. You have to call save() explicitly. <br>
    >> > q.save() <br>
    '''
    from django.utils import timezone
    q = Question(question_text="What's new?", pub_date=timezone.now())

    # Save the object into the database. You have to call save() explicitly. <br>
    q.save()

    text += str(q)+'<br>'

    text += '''# Now it has an ID. <br>
    >> > q.id <br>''' + str(q.id) + '<br>' + '''# Access model field values via Python attributes. <br>
    >> > q.question_text <br>''' +  str(q.question_text) +    ">> > q.pub_date <br>"+str(q.pub_date) + "<br>" + '''
    # Change values by changing the attributes, then calling save(). <br>
    >> > q.question_text = "What's up?"
    >> > q.save()'''
    q.question_text = "What's up?"
    q.save()

    text +='''# objects.all() displays all the questions in the database. <br>
    >> > Question.objects.all()<br>''' + html.escape(str(Question.objects.all()))

    return HttpResponse(text)

def part3_detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def part3_results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def part3_vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)


def part3_index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))

def part4_detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/part4_detail.html', {'question': question})

def part4_vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/part4_detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:part4_results', args=(question.id,)))

def part4_results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/part4_results.html', {'question': question})

class part4_IndexView(generic.ListView):
    template_name = 'polls/part4_index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class part4_DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/part4_detail.html'


class part4_ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/part4_results.html'

polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title_page }}</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:part3_detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/part4_detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:part4_vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/part4_index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:part4_detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/part4_results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:part4_detail' question.id %}">Vote again?</a>

polls/templates/polls/tutorials.html
{%  extends "polls/base.html" %}
{% block content %}
    <h3>Django tutorials</h3>
        <ul>
            <li><a href="part1/">Part 1</a> </li>
            <li><a href="part2/">Part 2</a> </li>
            <li><a href="part3/">Part 3</a> </li>
            <li><a href="part4/">Part 4</a> </li>
            <li><a href="part5/">Part 5</a> </li>
            <li><a href="part6/">Part 6</a> </li>
            <li><a href="part7/">Part 7</a> </li>
        </ul>
{%  endblock %}